#!/usr/bin/env node
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { CONFIG_FILE_NAMES, ConfigError, type ThreatModel } from "./engine/config.ts";
import { exceedsThreshold, isRuleInSuite, scan, type ScanResult } from "./engine/scanner.ts";
import type { Suite } from "./engine/types.ts";
import { formatText } from "./report/text.ts";
import { toSarif } from "./report/sarif.ts";
import { ALL_RULES, SYNTAX_ERROR_RULE } from "./rules/index.ts";
import { REPOSITORY_URL, TOOL_NAME, VERSION } from "./version.ts";

const HELP = `${TOOL_NAME} ${VERSION}: static analysis for GameMaker (GML) projects

Usage: gmlscan [path] [options]

  path                      Project or repository directory to scan (default: .)

Output:
  -f, --format <fmt>        text (default), json, or sarif
  -o, --output <file>       Write the report to a file instead of stdout
      --sarif <file>        Also write a SARIF report (for GitHub code scanning)
      --paths               Show source → sink data-flow paths in text output
      --no-color            Disable colours

Analysis:
  -c, --config <file>       Config file (default: .gmlscan.json in the scanned directory)
      --suite <name>        default | security-extended | security-and-quality | all
      --rule <id>           Only run this rule (repeatable)
      --runtime <version>   Target GameMaker runtime (default: from the .yyp IDEVersion)
      --threat-model <m>    remote and/or local (repeatable; default: remote)
      --fail-on <level>     Exit with 1 when findings at this level exist:
                            error (default), warning, note, none

Other:
      --list-rules          List all rules (use --format markdown for docs)
      --init                Write a starter .gmlscan.json
  -v, --version             Print the version
  -h, --help                Show this help

Suppress a finding with a comment:  // gmlscan-ignore-next-line gml/rule-id
Docs: ${REPOSITORY_URL}
`;

function listRules(format: string): string {
  const rules = [...ALL_RULES, SYNTAX_ERROR_RULE].map((r) => r.meta);
  if (format === "json") return JSON.stringify(rules, null, 2) + "\n";
  if (format === "markdown") {
    const suites: Suite[] = ["default", "security-extended", "security-and-quality"];
    const out = [
      "# Rules",
      "",
      "<!-- Generated by `gmlscan --list-rules --format markdown`. Do not edit by hand. -->",
      "",
      "| Rule | Severity | Category | Suites |",
      "| --- | --- | --- | --- |",
    ];
    for (const m of rules) {
      const inSuites = suites.filter((s) => isRuleInSuite(m, s)).map((s) => `\`${s}\``).join(", ");
      out.push(`| [\`${m.id}\`](#${m.id.replace(/[^a-z0-9]+/gi, "").toLowerCase()}) | ${m.severity} | ${m.category} | ${inSuites} |`);
    }
    for (const m of rules) {
      out.push("", `## ${m.id}`, "", `<a id="${m.id.replace(/[^a-z0-9]+/gi, "").toLowerCase()}"></a>`, "", `**${m.short}**`, "");
      const facts = [`Severity: ${m.severity}`, `Precision: ${m.precision}`, `Category: ${m.category}`];
      if (m.securitySeverity !== undefined) facts.push(`Security severity: ${m.securitySeverity.toFixed(1)}`);
      if (m.cwe?.length) facts.push(`CWE: ${m.cwe.map((c) => `[CWE-${c}](https://cwe.mitre.org/data/definitions/${c}.html)`).join(", ")}`);
      out.push(facts.join(" · "), "", m.help);
    }
    return out.join("\n") + "\n";
  }
  const width = Math.max(...rules.map((m) => m.id.length));
  return rules.map((m) => `${m.id.padEnd(width)}  ${m.severity.padEnd(7)}  ${m.tier.padEnd(8)}  ${m.short}`).join("\n") + "\n";
}

const STARTER_CONFIG = `{
  // GML Code Scanner configuration. See ${REPOSITORY_URL}#configuration
  // Query suite: default | security-extended | security-and-quality | all
  "suite": "default",

  // Turn rules off or change their severity: "off" | "error" | "warning" | "note"
  "rules": {
    // "gml/unused-function": "off"
  },

  // Paths to skip (globs, relative to this file)
  "ignore": [
    // "extensions/**",
    // "scripts/vendor_*/**"
  ],

  // Untrusted data to track: "remote" (network/HTTP) and optionally "local" (files, user input)
  "threatModels": ["remote"],

  // Variables with these prefixes are treated as declared globals
  "globalPrefixes": [],

  // Taint models for your own extensions, e.g. a custom networking DLL:
  "taint": {
    "sources": [
      // { "function": "net_receive_string", "kind": "remote" }
    ],
    "sinks": [
      // { "function": "my_dll_run", "arguments": [0], "kind": "command-injection" }
    ],
    "sanitizers": []
  },

  // Custom pattern rules ($X = metavariable, ... = anything)
  "patterns": [
    // {
    //   "id": "no-debug-overlay",
    //   "pattern": "show_debug_overlay(true)",
    //   "message": "Remove the debug overlay before release.",
    //   "severity": "warning"
    // }
  ]
}
`;

export function main(argv: string[]): number {
  let args;
  try {
    args = parseArgs({
      args: argv,
      allowPositionals: true,
      options: {
        format: { type: "string", short: "f" },
        output: { type: "string", short: "o" },
        sarif: { type: "string" },
        paths: { type: "boolean" },
        "no-color": { type: "boolean" },
        config: { type: "string", short: "c" },
        suite: { type: "string" },
        rule: { type: "string", multiple: true },
        runtime: { type: "string" },
        "threat-model": { type: "string", multiple: true },
        "fail-on": { type: "string" },
        "list-rules": { type: "boolean" },
        init: { type: "boolean" },
        version: { type: "boolean", short: "v" },
        help: { type: "boolean", short: "h" },
      },
    });
  } catch (e) {
    process.stderr.write(`gmlscan: ${(e as Error).message}\n\n${HELP}`);
    return 2;
  }
  const o = args.values;
  if (o.help) {
    process.stdout.write(HELP);
    return 0;
  }
  if (o.version) {
    process.stdout.write(`${VERSION}\n`);
    return 0;
  }
  if (o["list-rules"]) {
    const text = listRules(o.format ?? "text");
    if (o.output) {
      mkdirSync(dirname(resolve(o.output)), { recursive: true });
      writeFileSync(o.output, text);
    } else process.stdout.write(text);
    return 0;
  }
  const root = resolve(args.positionals[0] ?? ".");
  if (!existsSync(root)) {
    process.stderr.write(`gmlscan: path not found: ${root}\n`);
    return 2;
  }
  if (o.init) {
    const target = join(root, CONFIG_FILE_NAMES[0]);
    if (existsSync(target)) {
      process.stderr.write(`gmlscan: ${target} already exists\n`);
      return 2;
    }
    writeFileSync(target, STARTER_CONFIG);
    process.stdout.write(`Wrote ${target}\n`);
    return 0;
  }

  const format = o.format ?? "text";
  if (!["text", "json", "sarif"].includes(format)) {
    process.stderr.write(`gmlscan: unknown format "${format}" (expected text, json or sarif)\n`);
    return 2;
  }
  const failOn = o["fail-on"] ?? "error";
  if (!["error", "warning", "note", "none"].includes(failOn)) {
    process.stderr.write(`gmlscan: --fail-on must be error, warning, note or none\n`);
    return 2;
  }
  const suites = ["default", "security-extended", "security-and-quality", "all"];
  if (o.suite && !suites.includes(o.suite)) {
    process.stderr.write(`gmlscan: --suite must be one of ${suites.join(", ")}\n`);
    return 2;
  }
  const threats = o["threat-model"];
  if (threats?.some((t) => t !== "remote" && t !== "local")) {
    process.stderr.write(`gmlscan: --threat-model must be remote or local\n`);
    return 2;
  }

  let result: ScanResult;
  try {
    result = scan({
      root,
      configPath: o.config ? resolve(o.config) : undefined,
      suite: o.suite as Suite | undefined,
      onlyRules: o.rule,
      runtime: o.runtime,
      threatModels: threats as ThreatModel[] | undefined,
    });
  } catch (e) {
    if (e instanceof ConfigError) {
      process.stderr.write(`gmlscan: ${e.message}\n`);
      return 2;
    }
    throw e;
  }

  const sarifOf = () => JSON.stringify(toSarif(result, { toolName: TOOL_NAME, toolVersion: VERSION, informationUri: REPOSITORY_URL, scanRoot: root }), null, 2) + "\n";
  let report: string;
  if (format === "sarif") report = sarifOf();
  else if (format === "json") report = JSON.stringify({ version: VERSION, projects: result.projects, findings: result.findings, filesScanned: result.filesScanned, durationMs: Math.round(result.durationMs) }, null, 2) + "\n";
  else report = formatText(result, { color: !o["no-color"] && !o.output && process.stdout.isTTY === true && !process.env.NO_COLOR, showPaths: o.paths });

  if (o.output) {
    mkdirSync(dirname(resolve(o.output)), { recursive: true });
    writeFileSync(o.output, report);
    process.stderr.write(`Wrote ${result.findings.length} findings to ${o.output}\n`);
  } else {
    process.stdout.write(report);
  }
  if (o.sarif) {
    mkdirSync(dirname(resolve(o.sarif)), { recursive: true });
    writeFileSync(o.sarif, sarifOf());
  }
  return exceedsThreshold(result, failOn) ? 1 : 0;
}

const invokedDirectly = process.argv[1] && /(?:cli\.(?:ts|js)|gmlscan)$/.test(process.argv[1].replace(/\\/g, "/"));
if (invokedDirectly) process.exitCode = main(process.argv.slice(2));
